#pragma once

#include <cstddef>
#include <tuple> // IWYU pragma: keep
#include <utility>

namespace threadschedule::reflect
{

/**
 * @brief Descriptor for struct reflection (compile-time metadata).
 * Specializations are generated by THREADSCHEDULE_REFLECTION_DEFINE_STRUCT_REFLECT_HELPER; do not specialize manually.
 */
template <typename T>
struct descriptor
{
    static constexpr std::size_t size = 0;
};

template <typename T>
struct member_count
{
    static constexpr std::size_t value = descriptor<T>::size;
};

template <typename T>
inline constexpr std::size_t member_count_v = member_count<T>::value;

namespace detail
{
template <typename T, typename F, std::size_t... I>
void for_each_member_impl(T& obj, F&& f, std::index_sequence<I...> /*unused*/)
{
    using D = descriptor<T>;
    (void)(f(D::names[I], obj.*std::get<I>(D::ptrs)), ...);
}

template <typename T, typename F, std::size_t... I>
void for_each_member_impl(T const& obj, F&& f, std::index_sequence<I...> /*unused*/)
{
    using D = descriptor<T>;
    (void)(f(D::names[I], obj.*std::get<I>(D::ptrs)), ...);
}
} // namespace detail

/**
 * @brief Invoke @a f for each reflected member of @a obj.
 *
 * @a f is called as f(const char* name, MemberType& value) for each member.
 * Use THREADSCHEDULE_REFLECTION_DEFINE_STRUCT_REFLECT_HELPER to define the type (no separate REFLECT macro).
 */
template <typename T, typename F>
void for_each_member(T& obj, F&& f)
{
    using D = descriptor<T>;
    if constexpr (D::size > 0)
        detail::for_each_member_impl(obj, std::forward<F>(f), std::make_index_sequence<D::size>{});
}

template <typename T, typename F>
void for_each_member(T const& obj, F&& f)
{
    using D = descriptor<T>;
    if constexpr (D::size > 0)
        detail::for_each_member_impl(obj, std::forward<F>(f), std::make_index_sequence<D::size>{});
}

/**
 * @brief Name of the I-th reflected member (0-based). Only valid when I < member_count_v<T>.
 */
template <typename T, std::size_t I>
constexpr auto get_member_name() -> char const*
{
    static_assert(I < descriptor<T>::size, "member index out of range");
    return descriptor<T>::names[I];
}

} // namespace threadschedule::reflect

// --- Define struct and reflection in one macro; write each member once as (Type, name) ---

#define THREADSCHEDULE_REFLECTION_PAIR_FIRST(a, b) a
#define THREADSCHEDULE_REFLECTION_PAIR_SECOND(a, b) b
#define THREADSCHEDULE_REFLECTION_STRINGIZE(x) #x

#define THREADSCHEDULE_REFLECTION_DS_1(Name, p1)                                                                       \
    struct Name                                                                                                        \
    {                                                                                                                  \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                              \
    };                                                                                                                 \
    namespace threadschedule                                                                                           \
    {                                                                                                                  \
    namespace reflect                                                                                                  \
    {                                                                                                                  \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                            \
    {                                                                                                                  \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1)> ptrs{                   \
            &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1};                                                          \
        static constexpr char const* names[] = {                                                                       \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1)};                            \
        static constexpr std::size_t size = 1;                                                                         \
    };                                                                                                                 \
    }                                                                                                                  \
    }

#define THREADSCHEDULE_REFLECTION_DS_2(Name, p1, p2)                                                                   \
    struct Name                                                                                                        \
    {                                                                                                                  \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p2 THREADSCHEDULE_REFLECTION_PAIR_SECOND p2;                              \
    };                                                                                                                 \
    namespace threadschedule                                                                                           \
    {                                                                                                                  \
    namespace reflect                                                                                                  \
    {                                                                                                                  \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                            \
    {                                                                                                                  \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2)>                         \
            ptrs{&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2};    \
        static constexpr char const* names[] = {                                                                       \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p2)};                            \
        static constexpr std::size_t size = 2;                                                                         \
    };                                                                                                                 \
    }                                                                                                                  \
    }

#define THREADSCHEDULE_REFLECTION_DS_3(Name, p1, p2, p3)                                                               \
    struct Name                                                                                                        \
    {                                                                                                                  \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p2 THREADSCHEDULE_REFLECTION_PAIR_SECOND p2;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p3 THREADSCHEDULE_REFLECTION_PAIR_SECOND p3;                              \
    };                                                                                                                 \
    namespace threadschedule                                                                                           \
    {                                                                                                                  \
    namespace reflect                                                                                                  \
    {                                                                                                                  \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                            \
    {                                                                                                                  \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3)>                         \
            ptrs{&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3};                                                     \
        static constexpr char const* names[] = {                                                                       \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p3)};                            \
        static constexpr std::size_t size = 3;                                                                         \
    };                                                                                                                 \
    }                                                                                                                  \
    }

#define THREADSCHEDULE_REFLECTION_DS_4(Name, p1, p2, p3, p4)                                                           \
    struct Name                                                                                                        \
    {                                                                                                                  \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p2 THREADSCHEDULE_REFLECTION_PAIR_SECOND p2;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p3 THREADSCHEDULE_REFLECTION_PAIR_SECOND p3;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p4 THREADSCHEDULE_REFLECTION_PAIR_SECOND p4;                              \
    };                                                                                                                 \
    namespace threadschedule                                                                                           \
    {                                                                                                                  \
    namespace reflect                                                                                                  \
    {                                                                                                                  \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                            \
    {                                                                                                                  \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4)>                         \
            ptrs{&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4};    \
        static constexpr char const* names[] = {                                                                       \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p4)};                            \
        static constexpr std::size_t size = 4;                                                                         \
    };                                                                                                                 \
    }                                                                                                                  \
    }

#define THREADSCHEDULE_REFLECTION_DS_5(Name, p1, p2, p3, p4, p5)                                                       \
    struct Name                                                                                                        \
    {                                                                                                                  \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p2 THREADSCHEDULE_REFLECTION_PAIR_SECOND p2;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p3 THREADSCHEDULE_REFLECTION_PAIR_SECOND p3;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p4 THREADSCHEDULE_REFLECTION_PAIR_SECOND p4;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p5 THREADSCHEDULE_REFLECTION_PAIR_SECOND p5;                              \
    };                                                                                                                 \
    namespace threadschedule                                                                                           \
    {                                                                                                                  \
    namespace reflect                                                                                                  \
    {                                                                                                                  \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                            \
    {                                                                                                                  \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5)>                         \
            ptrs{&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5};                                                     \
        static constexpr char const* names[] = {                                                                       \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p5)};                            \
        static constexpr std::size_t size = 5;                                                                         \
    };                                                                                                                 \
    }                                                                                                                  \
    }

#define THREADSCHEDULE_REFLECTION_DS_6(Name, p1, p2, p3, p4, p5, p6)                                                   \
    struct Name                                                                                                        \
    {                                                                                                                  \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p2 THREADSCHEDULE_REFLECTION_PAIR_SECOND p2;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p3 THREADSCHEDULE_REFLECTION_PAIR_SECOND p3;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p4 THREADSCHEDULE_REFLECTION_PAIR_SECOND p4;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p5 THREADSCHEDULE_REFLECTION_PAIR_SECOND p5;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p6 THREADSCHEDULE_REFLECTION_PAIR_SECOND p6;                              \
    };                                                                                                                 \
    namespace threadschedule                                                                                           \
    {                                                                                                                  \
    namespace reflect                                                                                                  \
    {                                                                                                                  \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                            \
    {                                                                                                                  \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p6)>                         \
            ptrs{&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p6};    \
        static constexpr char const* names[] = {                                                                       \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p5),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p6)};                            \
        static constexpr std::size_t size = 6;                                                                         \
    };                                                                                                                 \
    }                                                                                                                  \
    }

#define THREADSCHEDULE_REFLECTION_DS_7(Name, p1, p2, p3, p4, p5, p6, p7)                                               \
    struct Name                                                                                                        \
    {                                                                                                                  \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p2 THREADSCHEDULE_REFLECTION_PAIR_SECOND p2;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p3 THREADSCHEDULE_REFLECTION_PAIR_SECOND p3;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p4 THREADSCHEDULE_REFLECTION_PAIR_SECOND p4;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p5 THREADSCHEDULE_REFLECTION_PAIR_SECOND p5;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p6 THREADSCHEDULE_REFLECTION_PAIR_SECOND p6;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p7 THREADSCHEDULE_REFLECTION_PAIR_SECOND p7;                              \
    };                                                                                                                 \
    namespace threadschedule                                                                                           \
    {                                                                                                                  \
    namespace reflect                                                                                                  \
    {                                                                                                                  \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                            \
    {                                                                                                                  \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p6),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p7)>                         \
            ptrs{&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p6,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p7};                                                     \
        static constexpr char const* names[] = {                                                                       \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p5),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p6),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p7)};                            \
        static constexpr std::size_t size = 7;                                                                         \
    };                                                                                                                 \
    }                                                                                                                  \
    }

#define THREADSCHEDULE_REFLECTION_DS_8(Name, p1, p2, p3, p4, p5, p6, p7, p8)                                           \
    struct Name                                                                                                        \
    {                                                                                                                  \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p2 THREADSCHEDULE_REFLECTION_PAIR_SECOND p2;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p3 THREADSCHEDULE_REFLECTION_PAIR_SECOND p3;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p4 THREADSCHEDULE_REFLECTION_PAIR_SECOND p4;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p5 THREADSCHEDULE_REFLECTION_PAIR_SECOND p5;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p6 THREADSCHEDULE_REFLECTION_PAIR_SECOND p6;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p7 THREADSCHEDULE_REFLECTION_PAIR_SECOND p7;                              \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p8 THREADSCHEDULE_REFLECTION_PAIR_SECOND p8;                              \
    };                                                                                                                 \
    namespace threadschedule                                                                                           \
    {                                                                                                                  \
    namespace reflect                                                                                                  \
    {                                                                                                                  \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                            \
    {                                                                                                                  \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p6),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p7),                         \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p8)>                         \
            ptrs{&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p6,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p7, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p8};    \
        static constexpr char const* names[] = {                                                                       \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p5),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p6),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p7),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p8)};                            \
        static constexpr std::size_t size = 8;                                                                         \
    };                                                                                                                 \
    }                                                                                                                  \
    }

#define THREADSCHEDULE_REFLECTION_DS_VA_NARGS_IMPL(_1, _2, _3, _4, _5, _6, _7, _8, N, ...) N
#define THREADSCHEDULE_REFLECTION_DS_VA_NARGS(...)                                                                     \
    THREADSCHEDULE_REFLECTION_DS_VA_NARGS_IMPL(__VA_ARGS__, 8, 7, 6, 5, 4, 3, 2, 1)

#define THREADSCHEDULE_REFLECTION_DEFINE_STRUCT_REFLECT_HELPER_DISPATCH(N, Name, ...)                                  \
    THREADSCHEDULE_REFLECTION_DS_##N(Name, __VA_ARGS__)
#define THREADSCHEDULE_REFLECTION_DEFINE_STRUCT_REFLECT_HELPER_INNER(N, Name, ...)                                     \
    THREADSCHEDULE_REFLECTION_DEFINE_STRUCT_REFLECT_HELPER_DISPATCH(N, Name, __VA_ARGS__)

/**
 * @brief Define a struct and its reflection in one place. Write each member once as (Type, name).
 *
 * No separate REFLECT macro; the member list is the single source of truth.
 *
 * @code
 *   THREADSCHEDULE_DEFINE_STRUCT_REFLECTION(Point, (int, x), (int, y));
 *   THREADSCHEDULE_DEFINE_STRUCT_REFLECTION(Config, (std::string, name), (int, threads), (bool, enabled));
 * @endcode
 *
 * Supports 1 to 8 members. Then use reflect::for_each_member(obj, lambda) as usual.
 */
#define THREADSCHEDULE_DEFINE_STRUCT_REFLECTION(Name, ...)                                                             \
    THREADSCHEDULE_REFLECTION_DEFINE_STRUCT_REFLECT_HELPER_INNER(THREADSCHEDULE_REFLECTION_DS_VA_NARGS(__VA_ARGS__),   \
                                                                 Name, __VA_ARGS__)

// --- BEGIN/END: same member list, but you can add methods between BEGIN and END ---

#define THREADSCHEDULE_REFLECTION_BEGIN_1(Name, p1)                                                                    \
    struct Name                                                                                                         \
    {                                                                                                                   \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;

#define THREADSCHEDULE_REFLECTION_BEGIN_2(Name, p1, p2)                                                                \
    struct Name                                                                                                         \
    {                                                                                                                   \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p2 THREADSCHEDULE_REFLECTION_PAIR_SECOND p2;

#define THREADSCHEDULE_REFLECTION_BEGIN_3(Name, p1, p2, p3)                                                            \
    struct Name                                                                                                         \
    {                                                                                                                   \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p2 THREADSCHEDULE_REFLECTION_PAIR_SECOND p2;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p3 THREADSCHEDULE_REFLECTION_PAIR_SECOND p3;

#define THREADSCHEDULE_REFLECTION_BEGIN_4(Name, p1, p2, p3, p4)                                                       \
    struct Name                                                                                                         \
    {                                                                                                                   \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p2 THREADSCHEDULE_REFLECTION_PAIR_SECOND p2;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p3 THREADSCHEDULE_REFLECTION_PAIR_SECOND p3;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p4 THREADSCHEDULE_REFLECTION_PAIR_SECOND p4;

#define THREADSCHEDULE_REFLECTION_BEGIN_5(Name, p1, p2, p3, p4, p5)                                                    \
    struct Name                                                                                                         \
    {                                                                                                                   \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p2 THREADSCHEDULE_REFLECTION_PAIR_SECOND p2;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p3 THREADSCHEDULE_REFLECTION_PAIR_SECOND p3;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p4 THREADSCHEDULE_REFLECTION_PAIR_SECOND p4;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p5 THREADSCHEDULE_REFLECTION_PAIR_SECOND p5;

#define THREADSCHEDULE_REFLECTION_BEGIN_6(Name, p1, p2, p3, p4, p5, p6)                                                \
    struct Name                                                                                                         \
    {                                                                                                                   \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p2 THREADSCHEDULE_REFLECTION_PAIR_SECOND p2;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p3 THREADSCHEDULE_REFLECTION_PAIR_SECOND p3;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p4 THREADSCHEDULE_REFLECTION_PAIR_SECOND p4;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p5 THREADSCHEDULE_REFLECTION_PAIR_SECOND p5;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p6 THREADSCHEDULE_REFLECTION_PAIR_SECOND p6;

#define THREADSCHEDULE_REFLECTION_BEGIN_7(Name, p1, p2, p3, p4, p5, p6, p7)                                           \
    struct Name                                                                                                         \
    {                                                                                                                   \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p2 THREADSCHEDULE_REFLECTION_PAIR_SECOND p2;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p3 THREADSCHEDULE_REFLECTION_PAIR_SECOND p3;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p4 THREADSCHEDULE_REFLECTION_PAIR_SECOND p4;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p5 THREADSCHEDULE_REFLECTION_PAIR_SECOND p5;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p6 THREADSCHEDULE_REFLECTION_PAIR_SECOND p6;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p7 THREADSCHEDULE_REFLECTION_PAIR_SECOND p7;

#define THREADSCHEDULE_REFLECTION_BEGIN_8(Name, p1, p2, p3, p4, p5, p6, p7, p8)                                       \
    struct Name                                                                                                         \
    {                                                                                                                   \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p1 THREADSCHEDULE_REFLECTION_PAIR_SECOND p1;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p2 THREADSCHEDULE_REFLECTION_PAIR_SECOND p2;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p3 THREADSCHEDULE_REFLECTION_PAIR_SECOND p3;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p4 THREADSCHEDULE_REFLECTION_PAIR_SECOND p4;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p5 THREADSCHEDULE_REFLECTION_PAIR_SECOND p5;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p6 THREADSCHEDULE_REFLECTION_PAIR_SECOND p6;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p7 THREADSCHEDULE_REFLECTION_PAIR_SECOND p7;                               \
        THREADSCHEDULE_REFLECTION_PAIR_FIRST p8 THREADSCHEDULE_REFLECTION_PAIR_SECOND p8;

#define THREADSCHEDULE_REFLECTION_END_1(Name, p1)                                                                      \
    }                                                                                                                   \
    ;                                                                                                                   \
    namespace threadschedule                                                                                           \
    {                                                                                                                   \
    namespace reflect                                                                                                   \
    {                                                                                                                   \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                             \
    {                                                                                                                   \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1)> ptrs{                    \
            &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1};                                                           \
        static constexpr char const* names[] = {                                                                        \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1)};                             \
        static constexpr std::size_t size = 1;                                                                         \
    };                                                                                                                  \
    }                                                                                                                   \
    }

#define THREADSCHEDULE_REFLECTION_END_2(Name, p1, p2)                                                                  \
    }                                                                                                                   \
    ;                                                                                                                   \
    namespace threadschedule                                                                                           \
    {                                                                                                                   \
    namespace reflect                                                                                                   \
    {                                                                                                                   \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                             \
    {                                                                                                                   \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2)>                         \
            ptrs{&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2};    \
        static constexpr char const* names[] = {                                                                        \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                             \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p2)};                             \
        static constexpr std::size_t size = 2;                                                                         \
    };                                                                                                                  \
    }                                                                                                                   \
    }

#define THREADSCHEDULE_REFLECTION_END_3(Name, p1, p2, p3)                                                              \
    }                                                                                                                   \
    ;                                                                                                                   \
    namespace threadschedule                                                                                           \
    {                                                                                                                   \
    namespace reflect                                                                                                   \
    {                                                                                                                   \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                             \
    {                                                                                                                   \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3)>                         \
            ptrs{&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3};                                                     \
        static constexpr char const* names[] = {                                                                        \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p3)};                             \
        static constexpr std::size_t size = 3;                                                                         \
    };                                                                                                                  \
    }                                                                                                                   \
    }

#define THREADSCHEDULE_REFLECTION_END_4(Name, p1, p2, p3, p4)                                                           \
    }                                                                                                                   \
    ;                                                                                                                   \
    namespace threadschedule                                                                                           \
    {                                                                                                                   \
    namespace reflect                                                                                                   \
    {                                                                                                                   \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                             \
    {                                                                                                                   \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4)>                         \
            ptrs{&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4};    \
        static constexpr char const* names[] = {                                                                        \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p4)};                             \
        static constexpr std::size_t size = 4;                                                                         \
    };                                                                                                                  \
    }                                                                                                                   \
    }

#define THREADSCHEDULE_REFLECTION_END_5(Name, p1, p2, p3, p4, p5)                                                       \
    }                                                                                                                   \
    ;                                                                                                                   \
    namespace threadschedule                                                                                           \
    {                                                                                                                   \
    namespace reflect                                                                                                   \
    {                                                                                                                   \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                             \
    {                                                                                                                   \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5)>                         \
            ptrs{&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5};                                                     \
        static constexpr char const* names[] = {                                                                        \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p5)};                             \
        static constexpr std::size_t size = 5;                                                                         \
    };                                                                                                                  \
    }                                                                                                                   \
    }

#define THREADSCHEDULE_REFLECTION_END_6(Name, p1, p2, p3, p4, p5, p6)                                                  \
    }                                                                                                                   \
    ;                                                                                                                   \
    namespace threadschedule                                                                                           \
    {                                                                                                                   \
    namespace reflect                                                                                                   \
    {                                                                                                                   \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                             \
    {                                                                                                                   \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p6)>                         \
            ptrs{&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p6};    \
        static constexpr char const* names[] = {                                                                        \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p5),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p6)};                             \
        static constexpr std::size_t size = 6;                                                                         \
    };                                                                                                                  \
    }                                                                                                                   \
    }

#define THREADSCHEDULE_REFLECTION_END_7(Name, p1, p2, p3, p4, p5, p6, p7)                                               \
    }                                                                                                                   \
    ;                                                                                                                   \
    namespace threadschedule                                                                                           \
    {                                                                                                                   \
    namespace reflect                                                                                                   \
    {                                                                                                                   \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                             \
    {                                                                                                                   \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p6),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p7)>                         \
            ptrs{&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p6,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p7};                                                     \
        static constexpr char const* names[] = {                                                                        \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p5),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p6),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p7)};                             \
        static constexpr std::size_t size = 7;                                                                         \
    };                                                                                                                  \
    }                                                                                                                   \
    }

#define THREADSCHEDULE_REFLECTION_END_8(Name, p1, p2, p3, p4, p5, p6, p7, p8)                                          \
    }                                                                                                                   \
    ;                                                                                                                   \
    namespace threadschedule                                                                                           \
    {                                                                                                                   \
    namespace reflect                                                                                                   \
    {                                                                                                                   \
    template <>                                                                                                        \
    struct descriptor<Name>                                                                                             \
    {                                                                                                                   \
        static constexpr std::tuple<decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p6),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p7),                          \
                                    decltype(&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p8)>                         \
            ptrs{&Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p1, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p2,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p3, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p4,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p5, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p6,     \
                 &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p7, &Name::THREADSCHEDULE_REFLECTION_PAIR_SECOND p8};    \
        static constexpr char const* names[] = {                                                                        \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p1),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p2),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p3),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p4),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p5),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p6),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p7),                              \
            THREADSCHEDULE_REFLECTION_STRINGIZE(THREADSCHEDULE_REFLECTION_PAIR_SECOND p8)};                             \
        static constexpr std::size_t size = 8;                                                                         \
    };                                                                                                                  \
    }                                                                                                                   \
    }

#define THREADSCHEDULE_REFLECTION_END_DISPATCH(N, Name, ...) THREADSCHEDULE_REFLECTION_END_##N(Name, __VA_ARGS__)
#define THREADSCHEDULE_REFLECTION_BEGIN_DISPATCH(N, Name, ...) THREADSCHEDULE_REFLECTION_BEGIN_##N(Name, __VA_ARGS__)

/* Extra indirection so N is expanded before BEGIN_##N / END_##N paste. */
#define THREADSCHEDULE_DEFINE_STRUCT_BEGIN_INNER(N, Name, ...)                                                          \
    THREADSCHEDULE_REFLECTION_BEGIN_DISPATCH(N, Name, __VA_ARGS__)
#define THREADSCHEDULE_DEFINE_STRUCT_END_INNER(N, Name, ...)                                                           \
    THREADSCHEDULE_REFLECTION_END_DISPATCH(N, Name, __VA_ARGS__)

/**
 * @brief Start a struct definition with reflected members. Add methods, then close with THREADSCHEDULE_DEFINE_STRUCT_END.
 *
 * Member list must be repeated in END (same as in BEGIN).
 *
 * @code
 *   THREADSCHEDULE_DEFINE_STRUCT_BEGIN(Point, (int, x), (int, y))
 *       void scale(int s) { x *= s; y *= s; }
 *       int sum() const { return x + y; }
 *   THREADSCHEDULE_DEFINE_STRUCT_END(Point, (int, x), (int, y))
 * @endcode
 */
#define THREADSCHEDULE_DEFINE_STRUCT_BEGIN(Name, ...)                                                                  \
    THREADSCHEDULE_DEFINE_STRUCT_BEGIN_INNER(THREADSCHEDULE_REFLECTION_DS_VA_NARGS(__VA_ARGS__), Name, __VA_ARGS__)

#define THREADSCHEDULE_DEFINE_STRUCT_END(Name, ...)                                                                    \
    THREADSCHEDULE_DEFINE_STRUCT_END_INNER(THREADSCHEDULE_REFLECTION_DS_VA_NARGS(__VA_ARGS__), Name, __VA_ARGS__)

// --- Single macro: members once + method body (wrap body in THREADSCHEDULE_BODY(...) so commas in methods are ok) ---

#define THREADSCHEDULE_BODY(x) x

#define THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS_1(Name, p1, body)                                                    \
    THREADSCHEDULE_REFLECTION_BEGIN_1(Name, p1) body THREADSCHEDULE_REFLECTION_END_1(Name, p1)
#define THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS_2(Name, p1, p2, body)                                                 \
    THREADSCHEDULE_REFLECTION_BEGIN_2(Name, p1, p2) body THREADSCHEDULE_REFLECTION_END_2(Name, p1, p2)
#define THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS_3(Name, p1, p2, p3, body)                                             \
    THREADSCHEDULE_REFLECTION_BEGIN_3(Name, p1, p2, p3) body THREADSCHEDULE_REFLECTION_END_3(Name, p1, p2, p3)
#define THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS_4(Name, p1, p2, p3, p4, body)                                        \
    THREADSCHEDULE_REFLECTION_BEGIN_4(Name, p1, p2, p3, p4) body THREADSCHEDULE_REFLECTION_END_4(Name, p1, p2, p3, p4)
#define THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS_5(Name, p1, p2, p3, p4, p5, body)                                    \
    THREADSCHEDULE_REFLECTION_BEGIN_5(Name, p1, p2, p3, p4, p5) body THREADSCHEDULE_REFLECTION_END_5(Name, p1, p2, p3, p4, p5)
#define THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS_6(Name, p1, p2, p3, p4, p5, p6, body)                                \
    THREADSCHEDULE_REFLECTION_BEGIN_6(Name, p1, p2, p3, p4, p5, p6) body THREADSCHEDULE_REFLECTION_END_6(Name, p1, p2, p3, p4, p5, p6)
#define THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS_7(Name, p1, p2, p3, p4, p5, p6, p7, body)                            \
    THREADSCHEDULE_REFLECTION_BEGIN_7(Name, p1, p2, p3, p4, p5, p6, p7) body THREADSCHEDULE_REFLECTION_END_7(Name, p1, p2, p3, p4, p5, p6, p7)
#define THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS_8(Name, p1, p2, p3, p4, p5, p6, p7, p8, body)                        \
    THREADSCHEDULE_REFLECTION_BEGIN_8(Name, p1, p2, p3, p4, p5, p6, p7, p8) body THREADSCHEDULE_REFLECTION_END_8(Name, p1, p2, p3, p4, p5, p6, p7, p8)

#define THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS_DISPATCH(N, Name, ...)                                                \
    THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS_##N(Name, __VA_ARGS__)
#define THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS_INNER(N, Name, ...)                                                   \
    THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS_DISPATCH(N, Name, __VA_ARGS__)

/**
 * @brief Struct with reflected members and methods in one macro. Member list written once; N = number of members.
 *
 * Wrap the method block in THREADSCHEDULE_BODY(...) so commas in method signatures don't break the macro.
 *
 * @code
 *   THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS(Point, 2, (int, x), (int, y), THREADSCHEDULE_BODY(
 *       void scale(int s) { x *= s; y *= s; }
 *       int sum() const { return x + y; }
 *   ))
 * @endcode
 */
#define THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS(Name, N, ...)                                                         \
    THREADSCHEDULE_DEFINE_STRUCT_WITH_METHODS_INNER(N, Name, __VA_ARGS__)
