name: Runtime Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S . -B build -DTHREADSCHEDULE_BUILD_TESTS=ON -DTHREADSCHEDULE_RUNTIME=ON -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure -C Release


