name: Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  # Test on Linux with multiple C++ standards
  linux:
    name: Linux (${{ matrix.os }}, C++${{ matrix.cpp_standard }}, ${{ matrix.compiler }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        cpp_standard: [17, 20, 23]
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            cc: gcc-11
            cxx: g++-11
          - compiler: clang
            cc: clang-14
            cxx: clang++-14
          - os: ubuntu-24.04
            cpp_standard: 20
            compiler: clang-18
            cc: clang-18
            cxx: clang++-18
          - os: ubuntu-24.04
            cpp_standard: 23
            compiler: clang-18
            cc: clang-18
            cxx: clang++-18
        exclude:
          # Clang 14 is too old for GCC 14's libstdc++ on Ubuntu 24.04 with C++20/23
          - os: ubuntu-24.04
            compiler: clang
            cpp_standard: 20
          - os: ubuntu-24.04
            compiler: clang
            cpp_standard: 23
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          sudo apt-get install -y g++-11 g++-12 g++-13
        elif [ "${{ matrix.compiler }}" = "clang-18" ]; then
          sudo apt-get install -y clang-18
        else
          sudo apt-get install -y clang-14 clang-15
        fi
    
    - name: Configure CMake
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_STANDARD=${{ matrix.cpp_standard }} \
          -DTHREADSCHEDULE_BUILD_EXAMPLES=ON \
          -DTHREADSCHEDULE_BUILD_TESTS=ON
    
    - name: Build
      run: cmake --build build --parallel
    
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --parallel

  # Test on Windows
  windows:
    name: Windows (C++${{ matrix.cpp_standard }}, ${{ matrix.compiler }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        cpp_standard: [17, 20, 23]
        compiler: [msvc]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Install Ninja
      run: choco install ninja
    
    - name: Configure CMake
      run: |
        $extraFlags = ""
        if ("${{ matrix.cpp_standard }}" -eq "17") {
          $extraFlags = "-DCMAKE_CXX_FLAGS=/permissive-"
        }
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=${{ matrix.cpp_standard }} -DTHREADSCHEDULE_BUILD_EXAMPLES=ON -DTHREADSCHEDULE_BUILD_TESTS=ON $extraFlags
    
    - name: Build
      run: cmake --build build --parallel
    
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --parallel

